# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    external_link:
        class: ChouettesBundle\Services\ExternalLinkFilter
        public: false
        tags:
            - { name: twig.extension }