whoami_index:
    path:     /
    defaults: { _controller: "ChouettesBundle:Whoami:index" }
    methods:  GET

whoami_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChouettesBundle:Whoami:edit" }
    methods:  [GET, POST]

whoami_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChouettesBundle:Whoami:delete" }
    methods:  DELETE
