chouettes_citation:
    resource: "@ChouettesBundle/Resources/config/routing/citation.yml"
    prefix:   /admin/citation

user_routing:
    resource: routing/user.yml
    prefix:   /

chouettes_modele:
    resource: "@ChouettesBundle/Resources/config/routing/modele.yml"
    prefix:   /admin/modele

chouettes_categorie:
    resource: "@ChouettesBundle/Resources/config/routing/categorie.yml"
    prefix:   /admin/categorie

chouettes_whoami:
    resource: "@ChouettesBundle/Resources/config/routing/whoami.yml"
    prefix:   /admin/whoami