#-----------------------------------------------------------------------------------------------------
#Appel route utilisateur/client
#-----------------------------------------------------------------------------------------------------

user_routing:
    resource: routing/user.yml
    prefix:   /

#-----------------------------------------------------------------------------------------------------
#Appel route admin
#-----------------------------------------------------------------------------------------------------

chouettes_modele:
    resource: "@ChouettesBundle/Resources/config/routing/modele.yml"
    prefix:   /admin/modele

chouettes_categorie:
    resource: "@ChouettesBundle/Resources/config/routing/categorie.yml"
    prefix:   /admin/categorie

chouettes_whoami:
    resource: "@ChouettesBundle/Resources/config/routing/whoami.yml"
    prefix:   /admin/whoami

chouettes_citation:
    resource: "@ChouettesBundle/Resources/config/routing/citation.yml"
    prefix:   /admin/citation

#-----------------------------------------------------------------------------------------------------
#Route accueil admin
#-----------------------------------------------------------------------------------------------------

admin_homepage:
    path:     /admin
    defaults: { _controller: ChouettesBundle:Default:admin }

#-----------------------------------------------------------------------------------------------------
#Route send mail
#-----------------------------------------------------------------------------------------------------

send_mail:
    path:     /mail
    defaults: { _controller: ChouettesBundle:Default:send }
    methods: [GET, POST]